# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  timeout: 5000
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: task_project
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: task_project_test
  pool: 5
  username:
  password:

production:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/production.sqlite3
